/** Small launcher metadata only. App implementations are imported after launch. */
export const desktopApps = [
  {
    id: "notes",
    category: "work",
    title: "Notes",
    description: "A local notebook",
    subtitle: "A place for your thoughts",
    keywords: "write text notebook scratchpad documents",
    icon: "journal",
  },
  {
    id: "calculator",
    category: "tools",
    title: "Calculator",
    description: "Work it out",
    subtitle: "A little room for numbers",
    keywords: "math arithmetic numbers calculate",
    icon: "calculator",
  },
  {
    id: "sketchpad",
    category: "create",
    title: "Sketchpad",
    description: "Draw something",
    subtitle: "Make your mark",
    keywords: "draw paint sketch canvas art image",
    icon: "palette",
  },
  {
    id: "focus",
    category: "work",
    title: "Focus",
    description: "Make a little time",
    subtitle: "One thing at a time",
    keywords: "timer pomodoro clock countdown break",
    icon: "timer",
  },
  {
    id: "tasks",
    title: "Tasks",
    category: "work",
    description: "One thing, then the next",
    subtitle: "Your local task board",
    keywords: "todo checklist kanban plan productivity",
    icon: "checklist",
  },
  {
    id: "markdown",
    title: "Markdown Pad",
    category: "work",
    description: "Words into documents",
    subtitle: "Write, preview, export",
    keywords: "editor markdown document writing preview",
    icon: "markdown",
  },
  {
    id: "json",
    title: "JSON Desk",
    category: "tools",
    description: "Make data readable",
    subtitle: "Format and inspect JSON",
    keywords: "json developer format validate minify data",
    icon: "braces",
  },
  {
    id: "converter",
    title: "Converter",
    category: "tools",
    description: "A different measure",
    subtitle: "Everyday unit conversions",
    keywords: "units length weight temperature convert distance",
    icon: "exchange",
  },
  {
    id: "worldclock",
    title: "World Clock",
    category: "tools",
    description: "Somewhere, it’s morning",
    subtitle: "Time around the world",
    keywords: "time zone city timezone clock world",
    icon: "clock",
  },
  {
    id: "colors",
    title: "Color Studio",
    category: "create",
    description: "Find your palette",
    subtitle: "Color, contrast, combinations",
    keywords: "color colour hex rgb hsl contrast palette design",
    icon: "swatch",
  },
  {
    id: "pixel",
    title: "Pixel Studio",
    category: "create",
    description: "Tiny squares, big ideas",
    subtitle: "A canvas for little worlds",
    keywords: "pixel art sprite draw paint png retro",
    icon: "grid",
  },
  {
    id: "sequencer",
    title: "Beat Lab",
    category: "create",
    description: "Make a little noise",
    subtitle: "Build your own rhythm",
    keywords: "music beat sequencer drums synth audio rhythm",
    icon: "music",
  },
  {
    id: "soundscape",
    title: "Soundscapes",
    category: "unwind",
    description: "Settle into a sound",
    subtitle: "Your own quiet corner",
    keywords: "ambient sound noise rain calm relax audio",
    icon: "headphones",
  },
  {
    id: "dice",
    title: "Dice Table",
    category: "play",
    description: "Leave it to chance",
    subtitle: "Roll something interesting",
    keywords: "dice random d20 d6 tabletop roll coin",
    icon: "dice",
  },
  {
    id: "sudoku",
    title: "Sudoku",
    category: "play",
    description: "Nine by nine",
    subtitle: "A small puzzle for your day",
    keywords: "sudoku number puzzle logic game",
    icon: "sudoku",
  },
  {
    id: "connect",
    title: "Four in a Row",
    category: "play",
    description: "Make the connection",
    subtitle: "A friendly game of four",
    keywords: "connect four 4 strategy game multiplayer",
    icon: "circles",
  },
  {
    id: "reversi",
    title: "Reversi",
    category: "play",
    description: "Turn the tables",
    subtitle: "Every move changes the board",
    keywords: "reversi othello board strategy game",
    icon: "reversi",
  },
  {
    id: "wordsearch",
    title: "Word Search",
    category: "play",
    description: "Hidden in plain sight",
    subtitle: "Find a little focus",
    keywords: "word search letters puzzle game find",
    icon: "letters",
  },
  {
    id: "typing",
    title: "Type Sprint",
    category: "play",
    description: "Find your rhythm",
    subtitle: "A race against yourself",
    keywords: "typing speed words wpm keyboard practice game",
    icon: "keyboard",
  },
  {
    id: "life",
    title: "Life Lab",
    category: "unwind",
    description: "Watch patterns grow",
    subtitle: "A tiny cellular universe",
    keywords: "conway life simulation cellular automata pattern",
    icon: "cells",
  },
  {
    id: "spirograph",
    title: "Orbit Studio",
    category: "create",
    description: "Draw a little infinity",
    subtitle: "Curves, color, and chance",
    keywords: "spirograph geometric generative art drawing curves export",
    icon: "spiral",
  },
  {
    id: "stopwatch",
    title: "Stopwatch",
    category: "work",
    description: "Catch every moment",
    subtitle: "Time, laps, and a fresh start",
    keywords: "stopwatch timer lap time track sports",
    icon: "stopwatch",
  },
  {
    id: "texttools",
    title: "Text Workshop",
    category: "tools",
    description: "A tune-up for text",
    subtitle: "Shape, count, and convert",
    keywords: "text case count replace base64 url encode decode developer",
    icon: "text",
  },
  {
    id: "decision",
    title: "Decision Wheel",
    category: "unwind",
    description: "Give chance a spin",
    subtitle: "A playful way to choose",
    keywords: "wheel random pick decision spinner names choose",
    icon: "wheel",
  },
] as const;
export const desktopAppCategories = [
  { id: "all", title: "All apps" },
  { id: "work", title: "Work" },
  { id: "create", title: "Create" },
  { id: "tools", title: "Tools" },
  { id: "play", title: "Play" },
  { id: "unwind", title: "Unwind" },
] as const;
export type DesktopAppId = (typeof desktopApps)[number]["id"];
