import { defineCollection, z } from "astro:content";

const articles = defineCollection({
  type: "content",
  schema: z.object({
    title: z.string(),
    description: z.string(),
    date: z.string(),
    tags: z.array(z.string()).default([]),
    readTime: z.string().optional(),
    featured: z.boolean().default(false),
    accent: z.enum([
      "amber",
      "cyan",
      "rose",
      "mist",
      "emerald",
      "sky",
      "violet",
      "lime",
      "teal",
      "indigo",
      "fuchsia",
      "pink",
      "orange",
      "red",
      "yellow",
      "blue",
      "slate",
      "stone",
      "zinc",
      "neutral",
      "purple",
      "green",
      "indigoDeep",
    ]).default("mist"),
    draft: z.boolean().default(false),
  }),
});

const projects = defineCollection({
  type: "content",
  schema: z.object({
    title: z.string(),
    summary: z.string(),
    role: z.string(),
    year: z.string(),
    stack: z.array(z.string()).default([]),
    impact: z.string().optional(),
    link: z.string().optional(),
    featured: z.boolean().default(false),
    accent: z.enum([
      "amber",
      "cyan",
      "rose",
      "mist",
      "emerald",
      "sky",
      "violet",
      "lime",
      "teal",
      "indigo",
      "fuchsia",
      "pink",
      "orange",
      "red",
      "yellow",
      "blue",
      "slate",
      "stone",
      "zinc",
      "neutral",
      "purple",
      "green",
      "indigoDeep",
    ]).default("mist"),
    draft: z.boolean().default(false),
  }),
});

export const collections = {
  articles,
  projects,
};
